version: "3.8"
services:
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NEWSAPI_KEY=${NEWSAPI_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend