name: Keep Render Awake

# Runs on a cron schedule: every 5 minutes
on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping front-end
        run: curl -fsSL https://localnews-front.onrender.com/ || true

      - name: Ping back-end
        run: curl -fsSL https://localnews-back.onrender.com/ || true
